### ISSUE TITLE
no highlighting in feature files

### ISSUE THREAD

**Issue by nhoyer-extern** [straighteight/SpecFlow-VS-Mac-Integration#18]
There is no highlighting in feature files anymore.

Env:
MacOs (10.14.3)
Visual Studio for Mac Community (7.8.3, build 2)
SpecFlow(2.4.1)

**Comment by Moshex** [comment]
This is open with the new updates from 01-08-2020. 
Here are my VS details:

Visual Studio Community 2019 for Mac
Version 8.4 (build 2657)
Installation UUID: 87bfc8d6-bb7e-4416-8725-c451ad424835
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.16.1.25 (issue-7441-d16-3-vsmac / 881172e73)

	Package version: 606000155

Mono Framework MDK
Runtime:
	Mono 6.6.0.155 (2019-08/296a9afdb24) (64-bit)
	Package version: 606000155

Roslyn (Language Service)
3.4.0-beta4-19562-05+ff930dec4565e2bc424ad3bf3e22ecb20542c87d

NuGet
Version: 5.3.0.6192

**Comment by sandyarmstrong** [comment]
This requires changes to the addin.xml file for this extension to support the `/MonoDevelop/Ide/Editor/TextMate` extension node. See https://github.com/mhutch/MonoDevelop.MSBuildEditor/pull/28 for an example.

**Comment by mikeyjones** [comment]
@sandyarmstrong looking at what you have said and based on Saamerm's pull request as well as how it was done in MSBuildEdtitor I changes the Textmate editor extensions to point to where our sublimetext extension lives and changed the properties of the sublime-package file to copy into the bin folder, like so:

`<Extension path="/MonoDevelop/Ide/Editor/TextMate">
        <Repository folderPath = "Bundles" />
</Extension>`

`<EmbeddedResource Include="Bundles\Cucumber.sublime-package">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
`

However, when I spin it up in Addin Maker I still do not any syntax highlighting for feature files. So I abstracted the .tmbundle file out of the package and tried with that file on its own but that didn't work either, and just in case I converted that file to JSON so it worked like MSBuildEdtitor, but still, that didn't show the highlighting.

What am I missing? My thought currently is to put it back to using the sublime-package,create the Addin and importing it into VS Mac in case the Addin Maker is the problem and it cannot see the sublime-package in the bin folder, which I'll try later, but any advice would be much appreciated as I'm running out of ideas

**Comment by Moshex** [comment]
@mikeyjones I have not tested with the latest updates yet, are you saying that with VS for mac's latest updates the issue is still open? do you know if the extension is getting recognized by the ide at all? 
also, I pinged @sandyarmstrong on the original VS ticket that I made here: https://developercommunity.visualstudio.com/content/problem/989950/no-highlight-syntax-in-specflow-feature-files-on-v.html
I hope that he can get back to us soon

**Comment by sandyarmstrong** [comment]
@mikeyjones can you show me a branch that has the changes you're talking about? MSBuildEditor has this:

```xml
    <None Remove="Syntax\*" />
    <AddinFile Include="Syntax\msbuild.json" />
```

Have you tried something similar? And yeah, make sure the folder here matches the `Repository folderPath` in the addin.xml.

**Comment by mikeyjones** [comment]
@sandyarmstrong I have just pushed my branch `feture_highlight` (spelled wrong in git oops). 

In our csproj we have:

`<ItemGroup>
    <AddinFile Include="Bundles\Cucumber.sublime-package">
      <LogicalName>Cucumber.sublime-package</LogicalName>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </AddinFile>
  </ItemGroup>`

`<None Remove="Bundles\Cucumber.sublime-package" />`

This looks similar to me, I added CopyToOutputDirectory as it looked like MSBuildEditor was doing the same based on the commit.

**Comment by Moshex** [comment]
@mikeyjones  are we still looking for @sandyarmstrong  help on this issue?

**Comment by Moshex** [comment]
@mikeyjones  @sandyarmstrong @saamerm I had no other choice but to update my environment today (09-02-2020) and there is still no highlighting in feature files anymore.  Is this just an issue with VS for mac and is there anything I can do to fix this? I can't imagine that I am one of the few people that use spec flow on mac?.

**Comment by mnohai-mdsol** [comment]
@Moshex you're not, I'm having the same issues.

**Comment by Moshex** [comment]
This issue is still present as of the date 11-24-2020, is there any hope to get this fixed?

**Comment by StephenMulryan** [comment]
Issue seems to be still present on the 12th of January. Any progress with it?

**Comment by prabhadevaraj** [comment]
I am also having the same issue that specflow steps are not highlighted and at least i am expecting to go to the respective step definition function on clicking the step in spec flow feature file.

**Comment by omerbozduman** [comment]
Is there any update no highlighting in feature files on Visual Studio on Mac ? @sandyarmstrong

**Comment by Moshex** [comment]
@omerbozduman I am not sure @sandyarmstrong could fix it is it not more on @mikeyjones ?

**Comment by sandyarmstrong** [comment]
@KirillOsenkov any thoughts here?

**Comment by omerbozduman** [comment]
I have started to use Specflow for one months ago and I have faced this highlighting issue. All other files and functions are working properly but feature file not. I couldn't use any functions on feature file(go to implementation, go to declaration ) but you can execute the feature file. I think I am not only one that using Specflow on Mac. I really don't understand why does specflow ( @SabotageAndi ) not create an official Specflow extension for Mac :(

**Comment by KirillOsenkov** [comment]
Hey all, I'm new here, I'm on the VSMac editor team. Apologies for the long delay.

Just as a quick note, Visual Studio for Mac has gotten a completely new editor starting with VSMac 8.0. We lost some compatibility with the features of the old editor. I'm not yet sure whether features of this extension are properly supported or not. The new editor does support TextMate, but I'd need to clarify which file formats are supported.

The new editor is now the same as in Visual Studio (for Windows), so if you write an extension for VS for windows chances are it would be relatively straightforward to get running on Mac as well.

I'm trying to understand how it all works and here are my findings. As far as I understand, the `.sublime-package` file is a zip file with a bunch of `.tmLanguage` and other files. First of all, I doubt that VSMac supports `sublime-package` files, so step one I'd recommend unzipping that file and checking in the files in the bundle instead.

Next, you need to verify that the .tmLanguage files are inside the .mpack, and the `/MonoDevelop/Ide/Editor/TextMate` points to the directory with the .tmLanguage files:

```
    <Extension path="/MonoDevelop/Ide/Editor/TextMate">
        <Repository folderPath = "Bundles" />
    </Extension>
```

Note that currently it points to the `Syntax` directory which I don't think is an existing directory.

After you do that and it still doesn't work, we can investigate further.

As a hint, you can peek inside the `Visual Studio.app` in Finder by choosing `Show package contents`. This way you can see how VSMac itself works. For example, our .tmLanguage files are located at `Contents/Resources/lib/monodevelop/AddIns/DisplayBindings/TextEditor.Cocoa/Starterkit/Extensions/objective-c/syntaxes/Objective-C.tmLanguage`.

**Comment by KirillOsenkov** [comment]
also FYI @gundermanc who is on the Visual Studio Editor team, he's our TextMate expert.

**Comment by gundermanc** [comment]
>First of all, I doubt that VSMac supports sublime-package files, so step one I'd recommend unzipping that file and checking in the files in the bundle instead.

This is definitely true of the shared TextMate implementation, which does not know about `sublime-package` format.

**Comment by omerbozduman** [comment]
Can we make a session or can you prepare a video record for solution and share with us ? I try all steps but nothing change. The same issue is there. @KirillOsenkov @gundermanc

**Comment by KirillOsenkov** [comment]
please share a branch where you tried my suggestions

**Comment by omerbozduman** [comment]
We are using Azure Devops instead of Github as a company therefore I couldn't share branch. But if you have free time we can do session on zoom and I can share my screen. You can check it.

**Comment by KirillOsenkov** [comment]
could you push a branch into this repo? my understanding is that the relevant highlighting code is in this repo

**Comment by omerbozduman** [comment]
No my code is not in this repo..

**Comment by KirillOsenkov** [comment]
An owner or maintainer of this repo will have to try my suggestions first in a branch and if that still doesn't work I can try and take a look at what's the next problem then. Alternatively anyone could fork this and try on their own.

**Comment by Moshex** [comment]
@mikeyjones Could you help with the changes needed to get the extension working again based on the new information?

**Comment by mikeyjones** [comment]
Thank you so much @funselaar  I have reviewed, tested and merged your commit to add syntax highlighting back in for VS for Mac.

I am waiting of the Microsoft team to add the mpack to VS for Mac. In the mean time if you want to install this manually you can do so by downloading the mpack from this release:

[Release 1.11.5](https://github.com/straighteight/SpecFlow-VS-Mac-Integration/releases/tag/v1.11.5.0-vsm8.10.14)

**Comment by Moshex** [comment]
The fix works for me as well, thank you so much  @funselaar I have waited for this fix for years now, I really hope you can publish this @mikeyjones
